/*
 * XOR.h
 * Neural network training and character recognition header
 * Defines functions for training a multi-layer perceptron (MLP) network
 * to recognize characters from OCR segmentation
 */

#ifndef XOR_H
#define XOR_H

/*
 * FileWriter - Save trained weights to file
 * @WeightIH: Input-to-Hidden layer weight matrix
 * @WeightHO: Hidden-to-Output layer weight matrix
 * @NumInput: Number of input nodes (256 for 16x16 bitmap)
 * @NumHidden: Number of hidden layer nodes (typically 300)
 * @NumOutput: Number of output nodes (59 for character classes)
 *
 * Writes all network weights to test.txt for later retrieval
 */
void FileWriter(double **WeightIH, double **WeightHO, int NumInput, int NumHidden, int NumOutput);

/*
 * FileParser - Load previously trained weights from file
 * @WeightIH: Input-to-Hidden layer weight matrix to fill
 * @WeightHO: Hidden-to-Output layer weight matrix to fill
 * @NumInput: Number of input nodes
 * @NumHidden: Number of hidden layer nodes
 * @NumOutput: Number of output nodes
 *
 * Reads weights from test.txt (previously saved training results)
 */
void FileParser(double **WeightIH, double **WeightHO, double NumInput, double NumHidden, double NumOutput);

/*
 * DisplayWeight - Print network weights for debugging (optional)
 * @WeightIH: Input-to-Hidden layer weights
 * @WeightHO: Hidden-to-Output layer weights
 * @NumInput: Number of input nodes
 * @NumHidden: Number of hidden layer nodes
 * @NumOutput: Number of output nodes
 */
void DisplayWeight(double **WeightIH, double **WeightHO, int NumInput, int NumHidden, int NumOutput);

/*
 * Training - Main neural network training algorithm
 * @Input: Training input patterns (NumPattern x NumInput matrix)
 * @Target: Target output vectors (NumPattern x NumOutput matrix)
 * @WeightIH: Input-to-Hidden layer weights (modified in place)
 * @WeightHO: Hidden-to-Output layer weights (modified in place)
 * @NumInput: 256 (16x16 character bitmap)
 * @NumHidden: 300 (typical hidden layer size)
 * @NumOutput: 59 (number of character classes)
 * @NumPattern: Number of training patterns (typically 59*20=1180)
 * @learningRate: Learning rate for weight updates (typically 0.5)
 * @MaxError: Target mean squared error threshold for convergence
 *
 * Implements backpropagation algorithm:
 *   1. Forward pass: Input -> Hidden -> Output
 *   2. Error calculation at output layer
 *   3. Backpropagation of errors to hidden layer
 *   4. Weight updates using gradient descent
 * Training continues until average error falls below MaxError or manual stop
 */
void Training(
    double **Input,
    double **Target,
    double **WeightIH,
    double **WeightHO,
    int NumInput,
    int NumHidden,
    int NumOutput,
    int NumPattern,
    double learningRate,
    double MaxError
);

/*
 * RandomInit - Initialize weights with random values
 * @WeightIH: Input-to-Hidden layer weights to initialize
 * @WeightHO: Hidden-to-Output layer weights to initialize
 * @NumInput: Number of input nodes
 * @NumHidden: Number of hidden layer nodes
 * @NumOutput: Number of output nodes
 *
 * Randomly initializes weights from -0.5 to 0.5 for training startup
 */
void RandomInit(double **WeightIH, double **WeightHO, double NumInput, double NumHidden, double NumOutput);

/*
 * InitialiseXOR - Initialize XOR-specific training data (placeholder)
 * @Input: Input patterns array
 * @Target1: First target pattern
 * @Value1: First input value
 * @Value2: Second input value
 * @Target: Target output value
 * @Target2: Second target value
 * @Indice: Index for storing pattern
 *
 * Legacy function - may not be used in current implementation
 */
void InitialiseXOR(double **Input, double **Target1, int Value1, int Value2, int Target, int Target2, int Indice);

/*
 * InitialiseInput - Load training input patterns from file
 * @Input: Input patterns matrix to fill (NumPattern x NumInput)
 * @NumPattern: Number of patterns to load
 * @NumInput: Number of input values per pattern (256)
 *
 * Reads character bitmaps from .car file generated by segmentation pipeline
 * Converts ASCII characters ('0'/'1') to numeric values
 */
void InitialiseInput(double **Input, int NumPattern, int NumInput);

/*
 * InitialiseTarget - Create target vectors for training
 * @Target: Target matrix to fill (NumPattern x NumOutput)
 * @NumPattern: Number of training patterns
 * @NumOutput: Number of output nodes (59 classes)
 *
 * Creates one-hot encoded target vectors:
 * Pattern i has Target[i][i%59] = 1, all others = 0
 * This associates each pattern with one of the 59 character classes
 */
void InitialiseTarget(double **Target, int NumPattern, int NumOutput);

#endif
